@Host = http://localhost:5266

### Create a new Product
POST {{Host}}/api/products
Content-Type: application/json

{
    "name": "Mechanical Keyboard",
    "description": "Clicky blue switches, RGB lighting",
    "price": 125.50,
    "stockQuantity": 50
}

### Get all Products
GET {{Host}}/api/products

### Get Product by Id
GET {{Host}}/api/products/1

### Register a new secure user
POST {{Host}}/api/auth/register
Content-Type: application/json

{
    "username": "AdminUser",
    "email": "admin@marketplace.com",
    "password": "SuperSecretPassword123!"
}

### Log in to get the JWT Token
POST {{Host}}/api/auth/login
Content-Type: application/json

{
    "email": "admin@marketplace.com",
    "password": "SuperSecretPassword123!"
}