@Host = http://localhost:5266
@Token = paste_token_here_temporarily_when_testing

### Create a new Product
POST {{Host}}/api/products
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "Gaming Mouse",
    "description": "Wireless, 20000 DPI",
    "price": 85.00,
    "stockQuantity": 100
}

### Get all Products
GET {{Host}}/api/products

### Get Product by Id
GET {{Host}}/api/products/1

### Update Product
PUT {{Host}}/api/products/2
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "Updated product",
    "description": "Testing updating a product",
    "price": 100.00,
    "stockQuantity": 1
}

### Delete product
DELETE {{Host}}/api/products/6
Authorization: Bearer {{Token}}




### Register a new secure user
POST {{Host}}/api/auth/register
Content-Type: application/json

{
    "username": "AdminUser",
    "email": "admin@marketplace.com",
    "password": "SuperSecretAdminPassword123!"
}

### Log in to get the JWT Token
POST {{Host}}/api/auth/login
Content-Type: application/json

{
    "email": "admin@marketplace.com",
    "password": "SuperSecretAdminPassword123!"
}




### Place an Order
POST {{Host}}/api/orders
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "productId": 1,
    "quantity": 3
}

### Get User Order history
GET {{Host}}/api/orders
Authorization: Bearer {{Token}}